# Generated by Django 5.0.14 on 2026-04-23 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0002_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('INCOME', 'Receita'), ('EXPENSE', 'Despesa')], default='EXPENSE', max_length=10),
        ),
    ]
